/**
 * Semantic LLM Answer Detection — augments heuristic detection with
 * LLM-based analysis for more robust AI-generated answer identification.
 *
 * Runs as a secondary check when heuristic score is in the "suspicious" range (25-70).
 * Uses a separate LLM call with low temperature for deterministic classification.
 */

import { logger } from "@/lib/logger";

interface SemanticDetectionResult {
  isLikelyAI: boolean;
  confidence: number; // 0-1
  signals: string[];
  provider: "gemini" | "openai" | "heuristic_only";
}

/**
 * Analyze a candidate response for AI-generated content using semantic analysis.
 * Checks for: structural patterns, hedging language, lack of personal experience markers,
 * suspiciously comprehensive coverage, and unnatural fluency patterns.
 */
export async function detectAIResponseSemantic(
  response: string,
  questionContext: string,
  previousResponses: string[] = []
): Promise<SemanticDetectionResult> {
  // Skip short responses — not enough signal
  if (response.split(/\s+/).length < 30) {
    return { isLikelyAI: false, confidence: 0.1, signals: [], provider: "heuristic_only" };
  }

  const prompt = `You are an AI-generated text detector analyzing interview responses.

QUESTION ASKED: "${questionContext}"

CANDIDATE RESPONSE: "${response.slice(0, 2000)}"

${previousResponses.length > 0 ? `PREVIOUS RESPONSES (for style consistency check):
${previousResponses.slice(-3).map((r, i) => `Response ${i + 1}: "${r.slice(0, 500)}"`).join("\n")}` : ""}

Analyze whether this response was likely generated by an AI (ChatGPT, Claude, etc.) or written/spoken by a human.

Check for these signals:
1. STRUCTURAL: Unnaturally organized (intro→body→conclusion), perfect paragraph structure, numbered/bulleted lists
2. HEDGING: Excessive qualifiers ("it's important to note", "there are several factors")
3. PERSONAL_ABSENCE: No personal anecdotes, feelings, mistakes, or "I" statements with specific context
4. COMPREHENSIVE: Suspiciously thorough coverage of all aspects (humans typically focus on what they know)
5. VOCABULARY: Consistently formal register, no colloquialisms, fillers, or self-corrections
6. CONSISTENCY: Response style dramatically different from previous responses (if available)
7. TEMPORAL: No references to specific dates, team members, project names, or concrete details

Respond in JSON only:
{
  "isLikelyAI": boolean,
  "confidence": number (0-1, where 1 = definitely AI),
  "signals": ["SIGNAL_NAME: brief explanation", ...]
}`;

  try {
    const { generateWithFallback } = await import("@/lib/llm-fallback");
    const result = await generateWithFallback({
      prompt,
      temperature: 0,
      maxTokens: 500,
    });

    let jsonStr = result.text.trim();
    if (jsonStr.startsWith("```json")) jsonStr = jsonStr.slice(7);
    if (jsonStr.startsWith("```")) jsonStr = jsonStr.slice(3);
    if (jsonStr.endsWith("```")) jsonStr = jsonStr.slice(0, -3);
    jsonStr = jsonStr.trim();

    const parsed = JSON.parse(jsonStr);
    return {
      isLikelyAI: !!parsed.isLikelyAI,
      confidence: Math.max(0, Math.min(1, parsed.confidence || 0)),
      signals: Array.isArray(parsed.signals) ? parsed.signals : [],
      provider: result.provider,
    };
  } catch (err) {
    logger.warn("[llm-answer-detector-semantic] Semantic detection failed, falling back to heuristic only", err as Record<string, unknown>);
    return { isLikelyAI: false, confidence: 0, signals: [], provider: "heuristic_only" };
  }
}
