import fs from "node:fs";
import { test, expect, Page } from "@playwright/test";
import { E2E_FIXTURES, STORAGE_STATE_PATHS } from "../fixtures/e2e-fixtures";

/**
 * Issue #14: signed-in hard navigation and refresh under the nonce CSP.
 *
 * Every visit is a direct page.goto (never a client-side transition) followed
 * by page.reload. The response must carry `script-src 'nonce-…'
 * 'strict-dynamic'` with no 'unsafe-inline', the document must hydrate (the
 * client-only "Loading..." guard shell must give way), every framework
 * script must carry the nonce, and the console must contain no CSP violation.
 * Nonces must differ between the two documents.
 */

const CSP_VIOLATION = /Content Security Policy/i;
const APP_SCRIPT_SRC = /^script-src 'nonce-[A-Za-z0-9+/=]{16,}' 'strict-dynamic'$/;

const fixturesRequired = process.env.E2E_AUTH_FIXTURES === "true";

function storageStateFor(envName: string, fallback: string): string | undefined {
  const explicit = process.env[envName];
  if (explicit) return explicit;
  return fs.existsSync(fallback) ? fallback : undefined;
}

const recruiterStorage = storageStateFor("E2E_RECRUITER_STORAGE_STATE", STORAGE_STATE_PATHS.recruiter);
const candidateStorage = storageStateFor("E2E_CANDIDATE_STORAGE_STATE", STORAGE_STATE_PATHS.candidate);

function requireStorage(kind: string, value: string | undefined): string {
  if (!value) throw new Error(`E2E_AUTH_FIXTURES=true but no ${kind} storage state was generated by the setup project`);
  if (!fs.existsSync(value)) throw new Error(`${kind} storage state ${value} does not exist`);
  return value;
}

const escapeRegExp = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

function scriptSrcOf(csp: string): string {
  return csp.split(";").map((d) => d.trim()).find((d) => d.startsWith("script-src")) ?? "";
}

function collectCspViolations(page: Page): string[] {
  const violations: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error" && CSP_VIOLATION.test(message.text())) violations.push(message.text());
  });
  return violations;
}

async function expectHydratedUnderNonce(page: Page, route: string, csp: string) {
  expect(scriptSrcOf(csp), `${route} script-src`).toMatch(APP_SCRIPT_SRC);
  expect(csp, `${route} must not allow unsafe-inline scripts`).not.toMatch(/script-src[^;]*'unsafe-inline'/);
  await expect(page.getByText("Loading...", { exact: true })).toHaveCount(0, { timeout: 30_000 });
  await expect(page).toHaveURL(new RegExp(`${escapeRegExp(route)}(?:\\?|$)`));
  const audit = await page.evaluate(() => {
    const scripts = Array.from(document.scripts);
    return {
      inline: scripts.filter((s) => !s.src).length,
      inlineWithoutNonce: scripts.filter((s) => !s.src && !s.nonce).length,
      srcWithoutNonce: scripts.filter((s) => s.src && !s.nonce).map((s) => s.src),
    };
  });
  expect(audit.inline, `${route} renders inline framework scripts`).toBeGreaterThan(0);
  expect(audit.inlineWithoutNonce, `${route} inline scripts without nonce`).toBe(0);
  expect(audit.srcWithoutNonce, `${route} script tags without nonce`).toEqual([]);
}

async function hardLoadAndRefresh(page: Page, route: string) {
  const violations = collectCspViolations(page);
  const first = await page.goto(route, { waitUntil: "domcontentloaded" });
  const firstCsp = first?.headers()["content-security-policy"] ?? "";
  await expectHydratedUnderNonce(page, route, firstCsp);

  const second = await page.reload({ waitUntil: "domcontentloaded" });
  const secondCsp = second?.headers()["content-security-policy"] ?? "";
  await expectHydratedUnderNonce(page, route, secondCsp);
  expect(secondCsp, `${route} nonce must be unique per response`).not.toBe(firstCsp);
  expect(violations, `${route} CSP violations`).toEqual([]);
}

test("recruiter: /dashboard and a dynamic job route hydrate on hard load and refresh under the nonce CSP", async ({ browser }) => {
  test.skip(!fixturesRequired && !recruiterStorage, "Requires E2E_RECRUITER_STORAGE_STATE");
  const context = await browser.newContext({ storageState: requireStorage("recruiter", recruiterStorage) });
  const page = await context.newPage();
  await hardLoadAndRefresh(page, "/dashboard");
  await hardLoadAndRefresh(page, E2E_FIXTURES.routes.jobDetail);
  await context.close();
});

test("candidate: /candidate/dashboard hydrates on hard load and refresh under the nonce CSP", async ({ browser }) => {
  test.skip(!fixturesRequired && !candidateStorage, "Requires E2E_CANDIDATE_STORAGE_STATE");
  const context = await browser.newContext({ storageState: requireStorage("candidate", candidateStorage) });
  const page = await context.newPage();
  await hardLoadAndRefresh(page, "/candidate/dashboard");
  await context.close();
});
