import fs from "node:fs";
import { test, expect } from "@playwright/test";
import { STORAGE_STATE_PATHS } from "../fixtures/e2e-fixtures";

/**
 * Issue #20: the /candidates sourcing table collapsed its three grid columns
 * on top of each other at 375 px. Below the md breakpoint the rows now stack
 * (with their own labels) and the column-header row is hidden; at 1280 the
 * twelve-column layout is unchanged. This spec proves both geometrically
 * rather than only through the golden screenshot.
 */

const fixturesRequired = process.env.E2E_AUTH_FIXTURES === "true";

function storageStateFor(envName: string, fallback: string): string | undefined {
  const explicit = process.env[envName];
  if (explicit) return explicit;
  return fs.existsSync(fallback) ? fallback : undefined;
}

const recruiterStorage = storageStateFor("E2E_RECRUITER_STORAGE_STATE", STORAGE_STATE_PATHS.recruiter);

function requireStorage(kind: string, value: string | undefined): string {
  if (!value) throw new Error(`E2E_AUTH_FIXTURES=true but no ${kind} storage state was generated by the setup project`);
  if (!fs.existsSync(value)) throw new Error(`${kind} storage state ${value} does not exist`);
  return value;
}

interface Box { x: number; y: number; w: number; h: number }
const overlaps = (a: Box, b: Box) => a.x < b.x + b.w && b.x < a.x + a.w && a.y < b.y + b.h && b.y < a.y + a.h;

test("/candidates sourcing rows stack at 375px and keep three columns at 1280px", async ({ browser }) => {
  test.skip(!fixturesRequired && !recruiterStorage, "Requires E2E_RECRUITER_STORAGE_STATE");
  const context = await browser.newContext({ storageState: requireStorage("recruiter", recruiterStorage) });
  const page = await context.newPage();

  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto("/candidates", { waitUntil: "domcontentloaded" });
  await expect(page.getByText("Loading...", { exact: true })).toHaveCount(0, { timeout: 30_000 });
  const rows = page.getByTestId("sourcing-row");
  await expect(rows.first()).toBeVisible({ timeout: 30_000 });

  // No horizontal page scroll at phone width.
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth);
  expect(overflow, "horizontal overflow (px)").toBeLessThanOrEqual(0);
  // Column headers only make sense once columns exist.
  await expect(page.getByTestId("sourcing-column-headers")).toBeHidden();

  const cellBoxes = async (row: ReturnType<typeof page.getByTestId>) => {
    const boxes: Box[] = [];
    for (const cell of ["sourcing-cell-name", "sourcing-cell-experiences", "sourcing-cell-schools"]) {
      const box = await row.getByTestId(cell).boundingBox();
      expect(box, cell).not.toBeNull();
      boxes.push({ x: box!.x, y: box!.y, w: box!.width, h: box!.height });
    }
    return boxes;
  };

  const rowCount = await rows.count();
  for (let i = 0; i < Math.min(rowCount, 3); i++) {
    const [name, experiences, schools] = await cellBoxes(rows.nth(i));
    // Stacked: each block starts below the previous one and none overlap.
    expect(experiences.y, `row ${i}: experiences below name`).toBeGreaterThanOrEqual(name.y + name.h - 1);
    expect(schools.y, `row ${i}: schools below experiences`).toBeGreaterThanOrEqual(experiences.y + experiences.h - 1);
    expect(overlaps(name, experiences), `row ${i}: name/experiences overlap`).toBe(false);
    expect(overlaps(experiences, schools), `row ${i}: experiences/schools overlap`).toBe(false);
    for (const box of [name, experiences, schools]) {
      expect(box.x + box.w, `row ${i}: cell inside the viewport`).toBeLessThanOrEqual(375);
    }
  }

  // Desktop layout unchanged: header row visible, cells side by side.
  await page.setViewportSize({ width: 1280, height: 900 });
  await expect(page.getByTestId("sourcing-column-headers")).toBeVisible();
  const [name, experiences, schools] = await cellBoxes(rows.first());
  expect(experiences.x).toBeGreaterThan(name.x + name.w - 1);
  expect(schools.x).toBeGreaterThan(experiences.x + experiences.w - 1);
  expect(Math.abs(experiences.y - name.y)).toBeLessThan(2);

  await context.close();
});
